# Site
repository: lizruonan/resume
favicon: images/favicon.ico

# Personal info
name: Elizabeth Zhao
title: Research Assistant at UC Irvine
email: elizaevit@gmail.com
website: https://lizruonan.github.io/blogs


# Social links
# twitter_username: #
github_username: lizruonan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: #
linkedin_username: ruonan-zhao
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/Avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Elizabeth. I am a mathematician who is passionate about learning
  and solving real-world problems. Currently, I am working in a mathematical biology lab
  at UC Irvine as a research assistant. My work is focusing on the mathematical side of biology problems,
  suchs as evaluating chormatin modifications using ODEs.

#  I am now interested in machine learning and looking to transition into this field. I am fascinated by

# Education Section
# educaton_title: Education


# Projects Section
# projects_title: Projects


# Experience Section
# experience_title: Experience


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
# - [Technical Blogs](https://lizruonan.github.io/blogs)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

darkmode: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
