# Site
repository: lizruonan/resume
favicon: images/favicon.ico

# Personal info
name: Elizabeth Zhao
title: Senior Network System Administrator
email: elizaevit@gmail.com
website: https://lizruonan.github.io/resume

# Social links
#twitter_username: #
github_username:  lizruonan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: #
linkedin_username: https://www.linkedin.com/in/ruonan-zhao/
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Elizabeth.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   - [Technical Blogs](https://lizruonan.github.io/blogs)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
